---
title: "The Ricardian Model with Diminishing Returns to Scale"
author: "Stephen Stretton"
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
bibliography: 0-OSC/skeleton.bib
link-citations: yes
---
# Paper 1: Ricardo in Hunter-Gatherer Land

# 1. Introduction




Ricardo's model of income distribution is interesting for many reasons.^[See @blaug1997economic, @ricardo1821principles] Ricardo assumes society-wide diminishing returns both on extending the margin of cultivation (extensive margin), and on the cultivation of existing pieces of land (intensive margin). In Ricardo's model, labour and capital taken together earn their marginal product. This links Ricardo's theory to neoclassical marginal productivity theory. Under assumptions of diminishing returns, the marginal product of labour is greater than average product. Land receives this surplus, so that the total product is fully distributed: labour and capital, taken together, receive their marginal product; land receives whatever is left over.

It remains in question, what is the most important fundamental factor that leads to a surplus (profit, interest or rent) over and above wages. Is it the existence of land that leads to a surplus? Or could there be a surplus even in a hunter gatherer society? And can we say anything about fair distribution and allocative efficiency in situations *without* land or capital ownership?

The goal here is theoretical rather than empirical: we are interested in the properties of idealised models of hunter-gatherer society not primarily as a model of hunting and gatherer societies, but as a way of isolating the theoretical effects of scale economies and diseconomies, independent of property ownership. Fundamentally we are interested in both *distribution* and *allocative efficiency*. Furthermore, our intention is not to justify our premises or even to entrench the use of commonly assumed premises by this work. The use of axioms in hypothetical theoretical papers should not be an implicit voting mechanism for axioms *qua* descriptors of the world.

# Definition of Model

We will imagine a hunter gatherer community under different economic conditions. Assume there are two activities: hunting and gathering.

In the model there are two 'produced' goods, meat which is hunted and nuts which are gathered. There is no money in the economy. Individuals are paid in meat or nuts, depending on what they have 'produced'. We measure M and N in physical terms, i.e. tonnes per year. Meat and Nuts are assumed to be substitutable, one can get food from either source. One tonne of meat has the same food value as one tonne of nuts. One tonne of groundnuts would take 24*365 hours to gather.

In all of the below we further assume that all individuals are homogenous and the population is defined as *Pop*. There is no government expenditure, although there may be social organisation, which we will come to. There is no capital or land; we will introduce a firm as an extension later. Thus we define output Y as the sum of meat M and nuts N. 

$$Y = M + N$$

## Production Function and Employment

Assume throughout that the characteristics of gathering are the same throughout: it is an activity that achieves a constant wage with constant returns to scale, and no technological progress. When people work, they always work with a constant level of effort. 

Production of nuts is assumed to have constant returns and individuals do not get tired. The production function for nuts is therefore 
$$N = G$$

Now assume there are diminishing returns to the application of labour to hunting, for the community as a whole. There is no ecological collapse, and no ecological constraints apart from those that may be read into our idea of diminishing returns, for example that it is easier to hunt the first zebra than later ones because hunting opportunities are limited. So hunting zebras leads to it being harder to hunt more, but not to any sort of ecological collapse. This would mean that as  the number of hunters is increased, the additional return in zebras per new man hour falls. As the number of people employed increases, the average number of zebras hunted per hour goes down. 

Assuming diminishing returns ($0<\alpha<1$), the production function for meat is therefore 
$$M = \beta H^\alpha$$

Our total production function is therefore

$$Y = N + M $$
So 
$$Y =  G + \beta H^\alpha$$

Implicitly this formulation ignores the natural resources that were used (the plants and the animals themselves), but since our interest is in the economics of diminishing returns, we ignore these. A true model of would consider the production function as Leontineff, needing both Labour and Natural Resources, but that is not required for our purposes.

Total employment as a proportion of full employment is given by:

$$ L = G + H $$

## Per Capita Formulation

We define per capita quantities using lower case letters:
$$y=\frac{Y}{Pop}$$

$$m=\frac{M}{Pop}$$
$$n=\frac{N}{Pop}$$


$$n = g$$

Defining $\gamma = \beta P_0 ^ \alpha$ we have

$$m = \gamma h^\alpha$$

And per capita income is:
$$y = m + p$$
$$y = g + \gamma h^\alpha$$

Employment is analogous to before:
$$ l = g + h $$

## 3. Social Welfare Optimisation

We explore two simple economic models for the 'social optimum'. Since population is fixed we do things on per capita basis.

## Maximisation of Income Under Constraints

Under this definition we maximise economic output under the constraint that labour employed is less or equal than full capacity. We maximise $y$ subject to $l \leq 1$.

## Free Time Optimisation

In this definition, people wish to satisfy their fixed dietary requirements $c$, measured in tonnes of food per year at minimum time expense. Welfare is equal to free time, as wants and total production are totally inelastic. Thus we maximise social welfare f per person, $f = 1 - h - g$ subject to $y = c$

## Utility Maximisation

As a more general case, we can consider that labour has some utility or disutility. 

## 4. A Simple Numerical Example

To illustrate, suppose that full employment is 2000 hours per year working. By gathering you get 0.5 kg of nuts per hour, or 1 tonne of nuts per fully employed year.

Let's assume that $\alpha = ½$, $\gamma = 1$, so $\beta=Pop^½$

Thus meat hunted per capita:
$$ m=h^½ $$

Nuts collected:
$$ n=g $$ 
Total income:
$$ y = h^½ + g $$

For simplicity, we will assume that calorific requirements are 1 tonne of food per year c = 1. Imagine we spending all our time gathering g=1, in that case we will get $y=n=1$ total income. Similarly if we spend all our time hunting $h=1$ we will also satisfy our requirements with $y=m=1$.

## Maximise Income
Now assume we maximise income 
$$ y=h^½+g $$
at full employment 
$$h + g = 1$$

Substituting our constraint into the model:

$$y = h^½ + (1-h)$$
Setting $\frac{dy}{dh} = 0$ we get: 
$$ \frac{h^{-½}}{2}- 1 = 0 $$
$$ \sqrt{h}=\frac{1}{2} $$
$$ h=\frac{1}{4} $$

At this optimum, our total income is given by:

$$ y = h^½ + (1-h) = \frac{1}{2} +\frac{3}{4} = \frac{5}{4} $$

## Maximise Free Time

Now assume we are maximising free time 
$f = 1 - g - h$

subject to production of 1

$m = 1 - n$ 
i.e. 
$h^½ = 1 - g$

So f = h^0.5 - h

Setting $\frac{df}{dh} = 0$ we get: 
$$½h^{-½} - 1 = 0$$
$$h^-½ = 2$$
So again we spend one quarter of the time hunting

$$ h=\frac{1}{4} $$

And this time half the time gathering
$$g= 1-h^½$$
$$g=\frac{1}{2}$$

Leading to total production of 

$$h^½ + g = \frac{1}{2}+\frac{1}{2} = 1$$

And total free time of 

$$ f = 1-h-g = \frac{1}{4}$$

## Comment and Extension to Optimising Utility 

The social optimum in general is given such that the amount of hunting done is such that the (social) marginal product of hunting is equal to that of gathering (which is unity). In the example above this social optimum is given by one quarter of the time spent hunting. 

On the other hand, the amount of time spent gathering can depend on what one wishes to optimise: total output, or free time, or, in general, utility (if there is assumed to be some utility or disutility of work). In each case we optimise hunting relative to gathering and then do as much gathering as is optimal relative to our objective.

In the Products section we therefore focus on the products (total products, average product, marginal product) to gathering and to hunting. We will talk in physical terms here.


## Maximise Individual Wages

Assume now that each hunter maximises his return and each hunter makes his average product as a wage. At the social optimum for hunting,
h=1/4, hunting wages are the total product divided by the time spent hunting.

$$ MPP = m/h = \frac{\gamma h^½}{h} = \gamma h^{-½} $$

This gives a wage of 2 for additional time spent hunting. So it makes sense for an individual hunter to continue to hunt until MPP=1  ie

$$ 1 = \gamma h^{-½} $$

$$ h = \gamma^2 $$

In our example $\gamma = 1$, so the average amount of hunting rises to 1 and we get a suboptimal result: everyone hunts all the time. This means that total product is 1 and  and total time spent is also 1. Whereas if we only hunt for $\frac{1}{4}$, we can either gather for $\frac{1}{2}$ and have $\frac{1}{4}$ free time, with the same output or we can gather for $\frac{3}{4}$, and have output of $\frac{5}{4}$ at full employment.

## 5. Discussion: Models of Wages

In the first instance, we assume that there is no economic benefit to collaborating as hunters. Each hunter is individual. If all the hunters are assumed to be the same and there are no taxes or firms or land ownership, we can assume that each hunter earns the average product of labour. 

## Case 1: Position is Important
Firstly, assume position is important. In this case the first people to start hunting will get more zebras than those that are late to the party. Assuming person 1 starts hunting first in the morning, then person 2, and so on. The people later on get lower wages than the ones starting off.

## Case 2: Equality
Second assume that position is not important. In this case, everyone gets the same wage. If it is just individuals then that wage would be the average product of labour. In this case we need to distinguish two different marginal products. Firstly there is the marginal product of a new hour considered as a community. This will be below the average product. 

It's quite often assumed that the marginal product for an individual producer will be equal to the marginal product for the society as a whole. But that is only the case if we do not have community diminishing returns. With community diminishing returns, a new person hunting also has an effect on the return of other hunters. The effect of an additional hunter acting individually includes not only the zebra that this person hunts, but also a reduction in the average product of the other hunters. To talk about the marginal product of the hunter is ambiguous therefore. If the marginal product is the marginal product to the individual hunter, that's one thing; if we mean the marginal product with respect to the community that is another.

In this case we have a collective action problem. There will be too much hunting! With community diminishing returns, a hunter has an external effect on other hunters: he reduces the average product of other hunters.


## Cast 3: One big firm
Third, imagine the whole of the hunting is arranged on a collective basis even if there is no real collaboration. There is a single community. Imagine then that workers are paid a base salary based on marginal product. Everyone gets the same wage based on the marginal product of an extra hour. But there is a surplus. Who will get that? It really depends who owns the firm.

# 6. The Dilemma
If there is limited ownership of firms (e.g. one monopolist), then there will be allocative efficiency but surplus extracted by the monopolist (unfair distribution). Whereas if everyone is paid their average product there will be too much hunting - ie a welfare gain from shifting from hunting to gathering.

# 7. Resolution
The resolution to the dilemma is simple. If there are diminishing returns then the marginal product will be below the average product. Therefore there will be a surplus. The solution is a two-factor model of distribution: both wages equal to marginal product and the surplus of average product over marginal distributed to all.

\newpage

# 8. Appendix: Marginal, Average and Total Products

We further define $g_i$ to be the time spend gathering by person $i$ and $h_i$ is the time spend hunting by person $i$.

## Gathering

The marginal and average products of gathering for individual i are equal to unity.

Total Gathering Product: 

$$ TP_g= \sum_i(n_i)=N=G $$

Gathering Product Per Person: 

$$ n_i = g_i = g $$

Social Marginal Product of Gathering Labour: 

$$ SMP_g= \frac{dN}{dg_i} = 1 $$

Average Product of Gathering Labour : 

$$ AP_g = \frac{N}{G} = \frac{G}{G} = 1 $$

Private Marginal Product of Gathering Labour:  

$$ PMP_g = \frac{dn_i}{dg_i} = 1$$

## Hunting

The productivities of hunting for individual i are:

Total Hunting Product: $$ TP_h= \sum_i m_i = M = H^\alpha $$

Social Marginal Product of Hunting Labour_i: 

$$SMP_i=\frac{d}{dh_i}(\beta.H^\alpha) = \frac{dH}{dh_i}.\frac{d}{dH}(\beta.H^\alpha) = \beta.\alpha.H^{\alpha-1}$$ 


Average Product: 

$$ AP = \frac{H^\alpha}{H}=H^{\alpha-1} $$

Marginal Private Product: 
$$ MPP = \frac{d}{dh_i}(AP*h_i)= \beta.h_i.(\alpha-1).H^{\alpha-2}+H^{\alpha-1} = \beta.H^{alpha-1}(1+(\alpha-1)(h_i/H))$$

$$ MPP = \beta.H^{alpha-1}(1+\frac{\alpha-1}{Pop}) $$

In the two extreme cases, if h_i=H, then the Marginal Private Product, 
$$MPP_{1 producer} = \beta.\alpha.H^{\alpha-1}$$

Whereas in the case of very many producers hi/H=1/N->0 then 
$$ MPP_{Many Producers}=\beta.H^{\alpha-1} $$

# 9. Per Capita Results

In per capita terms, the Social Marginal Product of Increasing the average quantity of hunting h is given by 

$$AP_h=\frac{\gamma.h^\alpha}{h}=\gamma.h^{\alpha-1} $$

$$SMP_h= Pop.SMP_{h_i}=\alpha.\gamma.h^{\alpha-1} $$

Marginal Private Product: 
$$ MPP = \beta.H^{alpha-1}(1+\frac{\alpha-1}{Pop}) $$

In the two extreme cases, if h_i=H, then the Marginal Private Product, 
$$ MPP_{1 producer} = \beta.\alpha.H^{\alpha-1} $$

Whereas in the case of very many producers:

$$ \frac{h_i}{H}=\frac{1}{N} \rightarrow 0 $$

Then:

$$ MPP_{Many Producers}=\beta.H^{\alpha-1}=\gamma h^{\alpha-1} $$


Then the total production function is given by:

$$ Y = \frac{1}{\nu} \int^{X_0} x^{\nu-1} dx $$ 

where $X$ is the position of the extensive margin. Thus

$$ Y= \frac{\alpha}{\nu}X ^{\nu} $$

 If we assume we apply the same amount of labour to each unit of land, then $L=X_{ex}$ and

$$Y= \frac{\alpha}{\nu}L^{\nu}$$

## Land and labour, with intensive and extensive margin (extensive) - Linear Form


In this example, land suffers from diminishing returns

$$y = (1-x).labour$$



## Land and labour, with intensive and extensive margin (extensive)

We now assume that in addition to the extensive margin, there is an intensive margin.

In this case, the productivity per unit area, y, is given by

$$ y=  e^{-\nu z} (1- e^{- \mu \rho}) $$

Intensive margin: 
$$ \frac{\partial y}{\partial \rho}= \mu e^{-\nu z - \mu \rho}=w $$



## Land and labour, with intensive and extensive margin

We now assume that in addition to the extensive margin, there is an intensive margin.

In this case, the productivity per unit area, y, is given by

$$ y= x^{\nu-1}{\rho}^{\mu} $$

Assuming that we apply labour to every margin until the marginal productivity of labour is w

$$ \frac{\partial y}{\partial \rho} = w $$

$$ \frac{\partial y}{\partial \rho} = x^{\nu-1}{\rho}^{\mu - 1} = w $$
$$ \mu . k.x^{\nu-1}= w.{\rho}^{1-\mu}  $$

$$ \rho =  (\frac{\mu}{w})^\frac{1}{1-\mu}.x^{-\frac{1-\nu}{1-\mu}} $$

So if $\nu=\frac{3}{4}$ and  $\mu=\frac{1}{2}$ then 

$$ \rho =  (\frac{\mu}{w})^\frac{1}{1-\frac{1}{2}}.x^{-\frac{1-\frac{3}{4}}{1-\frac{1}{2}}}=  (\frac{\mu}{w})^2.x^{-\frac{\frac{1}{4}}{\frac{1}{2}}} =   \frac{\mu^2}{w^2\sqrt x} $$


Substituting back into our production function, we have:

$$ y= x^{\nu-1}{\rho}^{\mu} = x^{-1/4}{\rho}^{1/2}=x^{-\frac{1}{4}}(\frac{\mu}{w}).x^{-\frac{1}{4}} = \frac{\mu}{w\sqrt x}$$
So there is no extensive margin.

$$N = \int_0^X \rho . dx= \int_0^X x^{-1/2} . dx=2aX^{\frac{1}{2}} $$
