---
title: "Screwed?!"
output: 
  tufte::tufte_handout: default
bibliography: 
- Library/PC/library.bib
- Library/Mac/library.bib
link-citations: yes
---

# CHAPTER 3: DESERT ISLAND ECONOMICS

## Summary

The purpose of this section is to take you on a second whirlwind tour of ideas in economics. This time, rather than travelling through history, we shall introduce these ideas through stories set on an imagined  group of islands, which we will term 'The Economic Archipelago' (informally, the 'Tea Islands').

# 3.1 Growth on Great Island: Adam Smith's Model

This economic fable demonstrates Adam Smith's model of growth through specialisation.

The largest island in the Tea Islands is 'Great Island', home to a few hundred people. All the islanders do the same thing, which is a bit of everything. Half the day is spent fishing (including maintenance of the boats and nets), and the other half is spent gathering nuts and berries. This yields 250 grams of fish and 250 grams of nuts and berries per person per day. In total, 500 grams of food is gathered, which is exactly equal to their dietary needs. 

## Specialization and Trade

Then a small group of fishermen discover something. They decide firstly, that they are *only* going to fish, and no longer participate in gathering berries. Whilst they like eating nuts and berries, they argue that they can catch enough fish and *trade* some of the fish with others for nuts and berries. They also split up tasks between themselves. Some of them make nets, others build bigger boats. They can catch more fish by splitting up tasks in this way. By collaborating and specializing they can double their productivity. Whereas before they could only make 500 grams of food per day, now they collectively can produce 1kg of food per day per fisherman. 

They now have some choices. They could catch fish all day (8 hours) and sell what they don't personally require for their own needs (the 'surplus'), saving this return or spending it on some luxuries. Another option is to cut down working hours by working only 4 hours per day. In the shorter working day they can still produce enough food to live on. In both cases we would say that the fishermen in the firm have higher hourly wages than before - twice what they were making before they decided to specialise. These higher wages reflect their higher productivity. 

This improvement in wages was generated by the fishermen and their initiative, and they are the beneficiaries of the new way of working. The economy has grown, but so far the additional prosperity has gone entirely to those fishermen. The price of fish relative to berries is unchanged. One kg of fish still sells for one kg of berries.

## Competition

At first, the benefits of improvements are captured by those that made the improvement. Our group of fisherman now live a life of relative luxury. Everyone else's material conditions are pretty much as they were before. The rest of the island's population does notice, however, that the fishermen who specialised seem to be getting richer. 

Pretty soon, some other islanders realise what the fisherman have done. They then follow suit, and adopt the new methods. Then even more fishermen notice what is going on and pile in as well. Fortunately the seas are plentiful. Once each fisherman has replicated the new improved double-productivity setup, they can all sell their surplus fish. 

But then something strange happens. Because the islanders only want to buy a certain quantity of fish, and now much more fish is being caught, the fishermen have to compete with each other to attract customers. So, they start to undercut each other in order to win market share. The price of fish in terms of berries starts to fall. 

## The Labour Theory of Value

To what price will the price of fish fall? It continues to fall until the point at which, under the new circumstances, it only just makes sense for workers to go fishing in the new fishing-conglomerates - i.e. when the wages from fishing in the new improved setup equilibrate to the wages for going gathering. In other words, the price of fish relative to berries will fall until it makes the same sense for someone to fish as to go collecting berries. This assumes of course that there is still value in eating some berries, perhaps for a varied diet. 

So now, the cost of fishing is expected to fall. In these new, changed circumstances, 1kg of fish (taking one day to collect) buys 0.5kg of berries (also taking one day to collect). This is the new, cheaper price of fish relative to berries.

## Widely Shared Prosperity?

If we add some numbers, we can make the improvement clearer.

At the end, people fish for a day to get one kilo of fish and perhaps go collecting for a day for half a kilo of berries. Two thirds of the people fish, and one third of the people collect berries. This is a change from the fifty-fifty split before the improvement in collective capabilities. 

The total average food production is (2/3)x1 + (1/3)x(1/2) = 5/6 or about 0.82kg. Thus the real wages per day have increased, from 0.5kg per eight-hour working day to 0.82kg of food per eight-hour day.

This is an example of the basic model of division of labour and competition. Let's now extend this model to the situation in which there is scarce land that is privately owned.

# 3.2 Rent on Private Land Island

Elsewhere in our Archipelago is an island where rabbits run free and are easy to hunt. On this island, lives a man, let's call him 'Man Friday', who has invented some laws of property. He defines himself the owner of this island, and has armed himself to make sure that nobody else can stay on the island or use its resources without his permission. He prepares to charge rent to anyone who turns up. This is thus an island of private property, which we will call 'Private Land Island'. 

One day a new man turns up, we can call him 'Robinson Crusoe'. This man has been living at sea in a fishing boat. Every (8-hour) day he fishes, he catches 1kg of fish, which we can assume are very nutritious. 

Crusoe arrives at Private Land Island, which is full of rabbits that are easy to hunt. He finds that if he works a whole 8-hour day, he can now catch 8kg of rabbits. Let's say that a rabbit is just as nutritious as a fish, and the work is just as pleasant. Because he only needs 1kg of food to live on, he can now work one hour per day and relax the rest of the time, perhaps by reading books on the division of labour. 

After the second day of fruitful hunting, Man Friday turns up to say hello. Fortunately, through a twist of fate, the two of them speak the same language. Friday is very happy that Crusoe has turned up. He invites Crusoe round to dinner. It's a very tasty dinner of rabbit-en-croute. Friday has many beautiful items on the wall, won from many years of selling rabbits to passing tradespeople. He even has a beautiful gun, and halfway through the meal, he gets it out of his gun holster, places it on the table to show it to Crusoe, and then puts it back in its holster.

Dessert is served. Friday has a family of servants who help him. Friday is saying how he is glad that Crusoe has joined the island. Half-way through the desert, Friday gets to the point. "Oh, about the rent" he says. "Would seven per day be ok?"

In that moment, Crusoe realises he has not been having a pleasant day after all. He had not even considered that Friday would charge him rent. There was space enough on the island for all. But Crusoe has few options. The best profession he had found up to now, working as a fisherman, earned 1 kg of food for a full day's work. Crusoe had thought that he would be in a position to work only one hour per day henceforward. But now he realised that his working hours would not change. The 8-hour shift of fishing to get one unit of fish is the same as the eight hours he would have to work to get 8kg of food in the new situation, of which 7kg would go to his landlord! He would still be working the same hours, and get the same pay. Admittedly, the new situation was a little better, as he was not subject to the storms and salt-corrosion of his boat, but it was not the bliss that he previously envisioned. 

It's interesting to note that the net wage after rent of our new arrival actually depends not on the conditions of the island, but rather on the conditions in his next best option, which is to go fishing. Suppose that fishing made 2kg of fish per 8-hour day (0.25 kg per hour). The landlord, observing this, would need to charge at most 6kg of rabbit per day in rent, since otherwise, Robinson Crusoe would always be better off fishing. This point is worth repeating: the well-being of someone in a given situation depends on the options they have available elsewhere.

A real-world example of this occured after the passing of the Enclosure Acts in England. The abolition of traditional peasant rights in England during the Enclosure Acts were the fundamental cause of poverty in big cities thereafter. Without the option of returning to the countryside to be a peasant, workers had no Plan B, and were not in a position to negotiate for better conditions in their urban environments. Therefore the wages paid by industrial capitalists needed only be sufficient to keep their wage-slaves alive, but no more - i.e. subsistence wages.

In economic terms, we say that the landlord can extract *rent* constituting the surplus over wages (in this case, the net resources kept by Crusoe once he has paid his rent).

## Differential Rent

Imagine the island is split into two domains of differential rabbit productivity. On the east side of the island, rabbits are plentiful, and a full day of hunting will yield 8kg of rabbits. On the west side, rabbits are less plentiful and only 4kg per day can be hunted. The landlord rents out both plots, but the rent charged on each must differ. Assume for now that the wage a person can make is still 1kg per day when fishing. Thus the landlord can charge 3kg of rabbits for residence on the less productive plot and 7kg of rabbits per day for residence on the more productive plot. As above, if the landlord attempted to charge more in rent, then their tenant would simply leave and return to fishing.

## Absolute Rent

Let's say that for some reason, there's a series of storms and the fishermen find it hard to catch fish. The landlords however have some spare resource - stored dried food - that they have accumulated over many years. They sell this food to the fishermen. In exchange the fishermen sell their boats to the landlords and rent them back. Now there is no rent-free way of earning a living. Either the islanders pay rent for a boat and fish, or they pay rent to stay on the island and hunt rabbits. In this situation, we say that land and other ways of earning a living are 'absolutely scarce'. They have been bought up by the wealthy landlords.

The amount of the landlord's revenue which comes from renting out boats versus the amount which comes from renting out hunting-rights to the rabbit hunters, will depend on the absolute scarcity of land and the absolute scarcity of labour.

In our current scenario of abundant labour (many islanders available to work), of the original 8kg of rabbits, only 1kg is retained by the hunter; the other 7kg are paid as rent for access to the landlord's hunting-grounds. The residual wages are not set at what the hunters can earn in a rent-free existence, but rather, the minimum that will keep them alive. 

In a scenario of scarce labour, this could change. This would require that the labourers (in this case, rabbit-hunters) have a choice of landlords to work for. If there are several islands with landlords and rabbits, but too few rabbit-hunters available to hunt all the rabbits produced by the islands, then the landlords will be forced to compete for the time and effort of the hunters. If they don't, they will receive no rent at all. In this case, the rabbit-hunters might be able to negotiate a deal with a landlord in which they retain two rabbits per day and pay the landlord only six rabbits (again assuming the hunter is able to bag eight rabbits a day). 

All this depends, of course, on the original rate of rabbit-hunting remaining sustainable; i.e. the fecundity of the rabbits and the available rabbit food on the islands must be such that the hunters' productivity of 8 killed rabbits per day doesn't overwhelm the ability of the rabbits to regenerate their populations. Also the rabbits' numbers mustn't get so high that they eat all the available greenery and cause a mass starvation. A dynamic equilibrium between rabbit population and the population of hunters is what's best for all concerned. 

## Capital

Let's say that our Robinson Crusoe sets aside some of his wages, in order to save for the future. He works for a bit and creates some rabbit traps. He has to invest some time in making them, but once he has done so, his productivity doubles from 1 rabbit per hour to 2 per hour; or from 8 rabbits per day to 16. It takes him one day to build the traps. The traps double his daily productivity to 16 rabbits per day. We can say that it increases his productivity by 8 rabbits. Each trap lasts 10 working days (80 hours) before having to be completely replaced. 

Does this investment make sense? Let's work it out. There's an original investment of 8 hours of time to create the trap, and this leads to 8 extra rabbits per day for 10 days. This is a total of 80 extra rabbits. I give up 8 rabbits in one day to construct my trap, and I get back 80 rabbits. Let's say that I borrow the resources to make the traps, so I borrow 8 rabbits to pay the rent and feed myself during the day I make the traps.

Thus my profit is 72 rabbits (assuming I continue to work a full day) each 10 day cycle. This is a profit of more than 7 rabbits per day, once the cost of my investment is taken into account.

At last Robinson Crusoe is happy! He is a great believer in hard work. He is working full days to pay the rent, and will continue to work full days. He can invest his time and create the traps, and reap the reward. After having paid back the time invested, there will be a surplus too! He can sell the spare rabbits to passing tradespeople or to Man Friday, and can build up assets.

We are assuming that Crusoe has some financial buffer, some wealth to tide him over for the day that he is building his trap and therefore not hunting. If rent is payable daily, he might be able to delay paying rent, he might be able to borrow some rabbits or other resources to pay rent, or he might invest his own stock of wealth until the investment pays back. 

Everything is going swimmingly well. He invests his time and he makes a surplus, and soon enough he's selling the spare rabbits to passing tradespeople and building up a store of value. 

But there's a catch. Man Friday comes round and observes what is going on. He takes some photos. And soon enough, some adverts go up in the Archipelago Gazette, the local newspaper for the islands. It's only after getting a copy from a trader on a passing ship that Crusoe sees them. The adverts say the following: 'Make a fortune hunting rabbits! Earn 16 rabbits per day.' He also reads the small print: 'Requires 8 rabbits investment to make traps; Rent: 14 rabbits per day.'

14 Rabbits! He's only paying 7 at the moment! What's coming? Sure enough, some visitors soon come around, friendly enough. The next day Man Friday invites Crusoe round for dinner again.... "About the rent"... he says. "I know you are enjoying staying here, but the market is changing. Market rents are going up. I had an offer the other day for someone to pay double what you are paying. Of course, I prefer to go with you, since I know you're a good reliable chap, so I won't chuck you out as long as you pay what the market is saying. It's only 14 rabbits per day. You still make a healthy 2 rabbits profit."^[Actually, it's only one rabbit after paying for your investments, and the cost of your own wages is not accounted for in that -- but the landlord didn't mention those things.]

So, Crusoe is back in his original position. He works an 8-hour day, and after rent, is again only left with 1kg rabbits in wages, enough for him to live on. He can't seem to get ahead! It sure seems like the concept of private *property* is the fundamental problem here, but as we will see, abolishing property causes its own problems...

# 3.3 Overhunting on Open Access Island

Let's now imagine another island. On this island, there are no property rights. Anyone can hunt for rabbits anywhere. And unlike the previous example, there is no landowner! Word gets around, and everyone comes to the island. 

In the beginning, everyone is happy. Wages, 8 rabbits per day, or one per hour, keep everyone in prosperity. There is no rent to pay. 

The problem this time is that too many people end up coming. Since the land is not owned by anyone, everyone hunts rabbits, and in the end too many rabbits are taken from the natural environment. The hunters soon deplete the common pool of rabbits on which everyone had relied. There is an ecological collapse. Soon there are few rabbits left. People have less food to eat. Those who can leave do so, and move to other islands. 

In contrast to the island with private property, people are poor, but there's no abusive rent collection. The absence of property rights has, however, caused a long-term impoverishment of the islanders, by causing a failure to allocate and enforce hunting-rights at sustainable levels. 

What we are learning through these scenarios is that the fair allocation of property rights is the key for protecting the rights and prosperity of the ordinary worker. 

# 3.4 Inequality on Special Island

Let's say now that hunters vary significantly in their skill level. There's a limited quantity of land, and a limited quantity of rabbits. But some people are much better than others at catching rabbits. Had there been unlimited rabbits or unlimited land, this wouldn't appear to be much of a problem. With limitations, however, there is a problem. The successful hunters can afford to pay the landlord more tribute (more in rent), and so their existence increases the price of land. Moreover, they put pressure on the rabbit population, harvesting more of the rabbits for themselves and leaving fewer for others. 

The landlord might impose a control by setting a limit on the total number of hunters allowed on the land. This may help somewhat, facilitating a process by which hunters compete to get rich by hunting ability rather than by merely owning land. However, in a limited environment, good hunters don't just benefit from their own hunting. They also indirectly impose costs on others. They raise the marginal price of land, and so make it more difficult for large families supported by rival hunters. As more individuals hunt rabbits, the resource becomes more scarce. 

This justifies what we call progressive taxation, to enable some degree of redistribution to compensate for the costs to the community of a more successful hunter. Progressive taxation means taxing people that have larger incomes at a greater proportional rate than people who have smaller incomes. 

# 3.5 Economic Justice on Dream Island

One of the islands on our archipelago is the island of our dreams. The fruit is bountiful, the water is clean, the people are happy. Everyone has a house or can build one with their own resources. Fisheries and forests are managed well. Some people are richer than others, but the difference isn't huge, and the people who are rich or high status are those that have contributed the most to society - in other words, the rewards which islanders receive are proportional to *contributive merit.* The community collaborates to ensure that the political system is not corrupt and governs the society well; the citizens trade with each other and with people on other islands. There is work for all, but no-one has to work uncomfortably long hours. The financial system supports beneficial activities - for example clean power and a recharging system for electric cars. Financially, people are secure; they have investments in the local factory, which, whilst its mostly robotised, provides everyone with a dividend to spend on the products that it and other factories produce.

Must this island just be the stuff of fantasy? Could it exist in the real world? Yes, and we hope in this book to outline a plan for achieving it. A good tax system, we claim, is the key tool towards achieving this heavenly island state - together with reforms of the social security system and some elements of the financial, education, and pensions systems. In this text our focus is on tax system reforms.

Now what can be said about taxation on this perfect island? Well, in simple terms, tax is fair, and fairly simple and straightforward for everyone to understand. In important ways, the tax system supports the rest of the economy - not only through ways in which revenues are spent, but also in the ways that the tax system creates appropriate incentives for the economy to function well. The incentives are to be in line with public purposes as well as private prosperity gained through genuine contributive merit. The two main ways the taxation system can be used toward such ends are *redistributive taxes* and *environmental taxes*. 

We will get to our Dream Island again, but first, an introduction to ideas which might solve some of the problems on the other islands in the archipelago.

## Getting to Dream Island

Let's now work out solutions to the problems we've encountered in our archepelago. It's easiest to solve problems before they get started - to set things up well from the start.

The problem of the landlord (Man Friday for example), extracting ever increasing rent from the islanders, for which he does no work. The first solution is a land value tax (LVT) - a tax on rent. With LVT, a landlord is taxed according to the surplus of each piece of land. He makes no unearned money. There's no such thing as a landlord any more, really. Land can still be purchased, but the person who owns and occupies it has to pay rent to the central authority. In other words, rent (money collected from tenants in excess of the landlord's costs) now accrues to the central authority, not to a private landlord. In our island archipelago, the central authority might be a democratic council elected on a one-person-one-vote basis. 

What does the central authority do with the taxes received (in our story: with the rabbits harvested)? There are two options: (1) The government could provide public services by paying people living on the island with rabbit-meat rations for doing useful things that benefit everyone. (2) The government could distribute rabbit-meat directly to the population, without requiring work in exchange.

What about over-hunting? A limited number of permits could be issued by the central authority, with fines and penalties levied against those who are caught ignoring the rules. Hunting rabbits could be constrained. Or put another way, a tax could be levied on hunting rabbits. On propertied land, it can be expected that the landowners/renters in charge of the land will themselves look after the rabbits on their own plots. If rabbits run freely between plots, there needs to be a joint solution agreed between all the land-owners or set by the central authority that constrains hunting.

# 3.6 Conclusions

In this chapter we dealt with *economics*. We worked out how economies can fail to have widely spread prosperity, and the reasons why they fail. In the real world we live in today is not merely an economy but a political *and* economic system. Rather than purely a theory of economics, we need a theory of politico-economic systems. In this book we do not have space to consider what such a theory would involve in great detail. Rather we suggest two guiding ideas: the win-win change, and the social contract. The win-win change ensures that the new policies *work for the pre-existing people and companies*, on the whole; the social contract gives a shared moral basis for what we are proposing.

We have seen a set of ideas concerning monopoly, land, external costs and the possibilities of progress in three different contexts: in the decision-making of a boat's captain, in the history of economic ideas, and in an imagined set of islands. In the next section we set out the central questions of this book in a bit more detail.
