---
title: "Screwed?!"
output: 
  tufte::tufte_handout: default
bibliography: 
- Library/PC/library.bib
- Library/Mac/library.bib
link-citations: yes
---

# CHAPTER 13: THE GLOBAL PERSPECTIVE: CLIMATE, FISCAL POLICY AND COLLECTIVE ACTION

Climate change is sometimes characterized as a ‘tragedy of the commons’ or ‘prisoner’s dilemma’ situation. In these game-theory setups, the self-interest of individual nations leads the world collectively to pursue a collectively sub-optimal outcome. This framing tends to implicitly assume a few features of the problem. 

The ‘agents’ are nation states (the EU sometimes will act in this capacity, but this is the exception), with the sovereignty to decide on and legally implement the outcome. In general, the interests faced by nation states are ‘national interest’. The ability of the world in general, or the nation states collectively, to impose the ‘collective interest’ is rather limited. Under these circumstances, game theory suggests that nations imposing their own interests leads to a sub-optimal collective outcome. This analysis makes certain assumptions, such as the existence of national sovereignty and of unitary and well-understood national interest at variance with international collective well-being. With these caveats, it does seem like a sensible first approximation.

The standard tragedy of the commons can be exacerbated by structural problems which are contingent on the policy frame adopted. For example, the Kyoto Protocol, the predecessor of the Paris Agreement, suffered various design flaws from a collective action perspective. 

A cap-and-trade system for carbon emissions, combined with international trading of emissions permits, has the following flaws. Firstly, asking countries to cap their absolute emissions uses a variable that is admittedly highly environmentally relevant, but it also targets a variable that is highly correlated to economic growth. Countries may see this as a constraint on their growth. 
Second, there may be real questions of transnational justice, since on a per-capita basis, rich western countries have higher levels of emissions than poorer countries. These considerations may suggest that no action be taken until the richer countries pay the poorer countries in compensation, and indeed may motivate countries to burn more fossil fuel, given a risk that they will be forced to reduce emissions later.

These issues may well have bite, but they amount, in effect, to a lack of agency and power at the global relative to the national level. 

Carbon taxes are a useful target for transnational incentives. Why? Because a carbon tax does not necessarily negatively affect the national interest, unlike an emissions target (which faster-than-expected emissions growth will blow through). One caveat is that, of course, nations do not always behave in a unitary and well-known national interest. If a carbon tax is very unpopular, a canny politician will not want to adopt it. Therefore, there is a need to incentivize policies that are both effective and useful. This brings us back to the need for measures to counteract unpopular consequences, such as the electricity feebates described in an earlier section.

Given these collective action design issues, there is a clear need to adopt a policy frame that is more conducive to action. One option that has been proposed (e.g. by Nordhaus) is a harmonized carbon tax framework. 

# Prioritizing Carbon Taxes in Real Political Contexts

A carbon tax is considered an optimal policy at least in part because it is reasonably full: it covers all sectors. From the perspective of optimal policy, the carbon tax should be as full and complete as possible. 
Another perspective is that we don’t live in the optimal situation. For a start, there are international collective action problems, and it is hard to know the exact best carbon tax rate.

Therefore, it may make sense to prioritize carbon taxes in particular sectors or countries. We can also distinguish between the carbon tax on new investment and the carbon tax on existing investments. 

In order to define financial conditionality or as part as a ‘climate club’ as proposed by William Nordhaus, it will be necessary to define a carbon price (either a carbon tax or an emissions trading scheme).

In order to impose carbon-tax conditionality it may be necessary to measure the level of the carbon tax. The simplest way to do this is to measure according to a simple index. Chris Hope has proposed such an index which might be termed the 'Hope Index'. It is defined as Level of a carbon price*Coverage of carbon pricing. So, a carbon tax of $100/tCO2 across the economy considered an index of 100. Countries that have a lower carbon tax rate, or less coverage. When a carbon tax is layered (only covers one part of the energy transformation process such as electricity generation), there needs to be some way of measuring this coverage. This requires more research.
