---
title: "Tax Heaven"
output: 
  tufte::tufte_handout: default
bibliography: Library/Mac/library.bib
link-citations: yes
---


# APPENDIX 1: CAKEONOMICS

In Chapter 4 we introduced an archipelago of islands and showed the different economic issues that come about. In this section we formalise these arguments in another way, in relation to the analogy of making a cake.

To illustrate clearly the issues that our society faces, we often use the analogy of the economy as a cake. 

We can generally classify the big economic problems into the following ten questions.

1. How big is the cake? The questions of *growth*.
2. How big a slice of the cake does each economic actor get? The problem of *distribution* of income and wealth between classes and individuals.
3. From what is the cake made? The problem of *allocation* of real resources to make the economic cake.
4. Does the cake as a whole rise to its full potential? -- The problem of achieving full employment and sufficient *demand*.
5. How much can we charge for our cake slices? The *price of goods*.
6. How much is the cake shop worth? The *price of assets*.
7. Do you want a slice of cake? *Rationality and its limits*
8. Does the cake keep? *Time*
9. Where's the cake shop? *Space*
10. The planetary cake *Energy and Living System*

Tax policy intersects all six of these issues. We want to design tax and welfare policy that leads to a successful economy in the long and in the short term, that allocates resources appropriately, and that leads to a just and appropriate distribution of income.

# A1.1 Growth: How big is the cake?

Growth is the problem of 'how big' the economy is, how much wealth and prosperity there is. First we have to define the problem. What should we measure? Francois Quesnay defined the 'tableau economique' which was the originator of the modern concept of Gross Domestic Product, which is the total value of goods and services produced in an economy. We will stick to real income as a measure of economic success, following Adam Smith in his Wealth of Nations, perhaps the first systematic approach to working out what makes the economic pie bigger. Whilst Smith's perspective (and that of growth theory generally) is about increasing the income of an economy, we might also consider the question of the stock of wealth in an economy. By wealth in this context, we don't just mean financial claims, but rather the wealth of the whole country or world. 

There are, broadly, three proposed solutions to the problem of growth: accumulation, division of labour, and capability more generally.

Growth can be driven by accumulation: more capital; more people (population growth); or more nature ie the extraction of more material energy or other materials from the earth. In each of these cases, we are explaining more 'output' from more 'input'. How much of economic growth can be explained by more input? Solow defined his famous growth model where he considered how much of economic growth could be explained by capital and labour accumulation. His result: accumulation could only explain a small amount of economic growth. He named the residual 'technology'; but in fact this residual consists of a number of factors which we now consider.

Adam Smith made  use of the principle of division of labour in his Wealth of Nations [@smith1776wealth]. By dividing up the manufacture of pins into many steps, each step could be more productive. Smith's competitive approach could be contrasted with earlier Arab economist Ibn Khaldun, considered the division of labour as a way for cooperation to enhance the goods provided in a society  [@Olah2018]. Division of labour makes each step of the production process more efficient, requiring less labour for a given level of output. 

Whilst a 'labour theory of value' cannot explain all the differences in prices between goods, labour is generally the most important element in the prices of goods. As Samuelson, quoted in Blaug [@blaug1997economic] puts it "The operational significance of a one factor model is the importance it gives to technology". Translating this into simple English, as labour is the most important factor, using less of it can raise real incomes. When we divide labour, we increase efficiency. Two people doing separate parts of a more finely divided production process is more efficient than one person doing both tasks. We can also say, therefore, following Smith, that increasing the *size* of a market can also increase wealth, because a larger market, with lower transportation and exchange costs, can divide labour more finely. This is also an argument for free trade.

We can also say that technology is a public good, created by R&D and science. Finally, we should talk about capability more generally. Charles Babbage argued that the economic success of a society was dependent on a 'capability triad': production capabilities, business organisation and economic governance [@Hilton2017]. Therefore success requires a certain amount of activism by government: to promote capability in industry, good management and good governance.

## Implications for the Tax and Welfare System

What are the implications of all this for taxation policy? Smith himself argued that a good tax system should minimise the discouragement that a tax causes to economic activity.

We can say ourselves the following things:

1. Tax should minimise the barriers to division of labour; and should not discriminate in favour of companies over markets between individuals;
2. Tax should encourage the accumumation of skill and physical capital investment^[this latter point is not uncontroversial given increasing automation, and depends on wide ownership of capital]
3. Tax should encourage the development of capability.

# A1.2 Distribution: How big a slice does each person get?

The final big question that we consider is that of distribution. Distribution typically refers classically to the distribution of the economic cake between those that own land (landowners), those that own companies or other non-land wealth (capitalists) and those that only own their own working time (labour). We covered this in Chapter 1.6, so we will only make a few more comments here.

It is important to distinguish between justified and unjustified Wealth. Justified wealth consists in wealth that is derived from work, the creation of some product of value (or at least wanted) in society - the provision of goods and services. Unjustified wealth consists in effectively extracting the wealth of others. Such wealth is not acquired by the addition of anything valuable to the economy, but rather is gained from endowments or second-hand value creation. 

## Who Really Pays A Tax? Economic Incidence of Tax and Spending

Another important aspect of distribution is who pays a tax. Taxes are not always paid by those who are the immediate tax payer. In general the theory of incidence suggests that taxes are paid by the most inflexible factor: e.g land, other monopolies.

But public spending also does not always benefit economically the initial recipient. If public services are shared over some area where high quality land is scarce, then it will be the landowner who benefits, not the direct individuals who are tenants. Whilst the advantages of living in an area may go up with better public services, if landlords can charge higher rents in so doing, then the benefit of increased spending may go on increased rent. The Henry George theorem states, that under certain conditions, the beneficiary of all public spending is the landowners. This effect can be seen in practice with a new railway link. In fact, in Hong Kong, new links on the metro are financed by purchase of land near new stations. This provides another justification for taxing the unearned increment on land value.

## Persistent Profit from Companies

We have already discussed land in some detail. But we should also consider taxing other forms of profit, from companies. Some situations are natural monopolies; others are government created types of monopoly, and finally the dynamics of some production and sales processes naturally favours larger firms.

All situations where an individual or company has some non-replicable advantage can make something similar to rent. Profits can be competed away, rents are permanent. So we sometimes see the phrase 'rent' used in other situations than land, to mean the permanent component of profit. Warren Buffett makes this explicitly: he seeks companies that have a 'moat' to their 'castle', the castle being the profits made and the moat being the barriers to other companies competing away their profit. 

Taxes on profits, especially persistent profits, therefore make a lot of sense. We need to find a way that these profits taxes can't be taxed away.  Finally some firms such as Amazon make a return without making profit at all, by capturing market share they force out the opposition creating a global form of monopoly. So we will need to find a way to tax corporate wealth independent of profit. 

- Monopoly (could add to example earlier)
- Urban Land and Urban Land Rent

# A1.3 Allocation: From What Should the Economic Cake Be Made?

Governments influence the allocation of economic activity two main ways:

- First, governments spend money, therefore directly allocating what is done. They can also lend themselves or direct lending of the financial sector.
- Second, governments create the systems of tax and regulations which guide and directs the private sector.

In both senses, it's important that public goods are taken into account.

Economists often talk of value, by which they usually mean *private value*, which is the benefit generated by someone producing goods and services; and the benefit the consumer receives from buying them. Economists also speak of 'public goods' as those which have various characteristics. The first is that we can't avoid consuming them for better or worse. Also, consuming them does not preclude others from doing so (they are non-exclusive). Some public goods have neither of these characteristics, yet are still provided publicly.

All these reasons provide justification for public goods to be created and shared. Taxation is a way of funding those public goods. However, tax and spending is not the only way of providing public goods. Charities, civic society, individuals and culture can all provide public goods, and the provision of private goods and services as a whole can also be seen as a public good. For example, a locality where there are lots of easily available shops and other services is a kind of public good, because those private goods assist each other in benefiting the people who live there.

## Implications for the Tax and Welfare System

Creating the right incentives is key to influencing people to behave in a beneficial manner, and the tax system is largely a system of incentives and disincentives. Strangely, the current system incentivises activities we don't want and disincentives activities we do want. To improve people's choices, we have to change these incentives.  We should tax activities that are harmful to others or to the natural environment. This will both reduce/discourage the negative activity and make the actor 'internalise' the harm done by the activities. It will help create a fair playing field for less harmful competitors. There are two types of harmful activity which could be taxed:

- Activities that harm others or the environment: in these cases activities should either be banned (now or in a forward-looking sense) or taxed;
- Activities that harm the individuals themselves such as smoking or excessive sugar and meat consumption: here we need to create a benevolent environment for the individual that does not encourage the harmful activities. This includes having the right incentives especially for the corporate sector (e.g. a sugar tax impacting the composition of breakfast cereals).

# A1.4 Demand: Does the cake rise to its full potential?

Tax and Welfare are important. They are the principal tools by which governments raise revenue to provide public goods and support the poor.  However, taxes must be justified on some basis, if they are to exist at all. The common answer is that tax is needed to pay for common services. 

More generally, taxes are needed because two classes of goods exist in society: private and public. Private goods are those provided by the market economy: i.e. by individuals and companies when acting in a commercial capacity. Public goods are those that benefit us all, like a secure country and public infrastructure. We need taxes to pay for and regulate public goods. The tax system is intended to raise revenue for the provision of public services. 

But this is not the only viewpoint on the primary purpose of taxation. 

## MMT

Modern monetary theory (MMT) argues that the purpose of taxation is slightly different. The purpose of taxation according to MMT is to mop up money that is created by public spending. This is an unusual perspective because most people believe that the government needs to tax or borrow money before they can spend it. From the perspective of MMT by contrast, money is simply a collection of tokens acceptable in the payment of taxes and created by public spending in the first place. 

The purpose of taxation within MMT is to control inflation. If more money is issued than there is demand for, the value of that money will degrade relative to the real economy. This means, that even with an MMT perspective, there presumably needs to be some taxation. MMT supporters generally believe that the government can and should run a fiscal deficit but that this deficit is limited by the effect on inflation rather than some requirement for 'austerity' to keep the public debt down. 

So, even proponents of MMT believe we need taxation. But taxation is not the only way to fund the government. There are many options, including fees for govt services, charging rent etc. But the usual options are taxation, issuing bonds, or printing money. On a basic level, we need to tax roughly as much as the government spends. There could be a fiscal deficit, but it should be of a moderate level in normal times.

## Fiscal Deficits

The MMT perspective is similar to thar of 'functional finance' as described by Abba Lerner. According to this perspective, the purpose of the government deficit is to keep the economy running at full capacity [@Lerner1943]. Government debt will take care care of itself as long as the economy is growing. This is a perspective born out by the post-war experience. (See part 10)

What we are dealing with here is the problem of the correct amount of (effective) demand. Effective demand is really the amount of spending power that agents have in the economy. The government can influence this in two ways: through fiscal and monetary policy. Fiscal policy is the overall budget balance of the government. When governments borrow more than they spend, this increases the budget deficit, which also increases the spending power of those in the economy. 

Monetary policy involves changes to interest rates, which effects asset values. It also effects the exchange rate. In low-interest rate environments, fiscal policy is particularly effective and monetary policy less so ('pushing on a string' in Keynes's vivid phrase).

Thus these two forms of macroeconomic policy (fiscal policy and monetary policy) can both be used to help guide the economy, and solve the short term problem of effective demand i.e., 'how much does the cake rise'.

Our goal here is not to discuss fiscal policy specifically: we assume here that the overall fiscal balance (the difference between spending and taxation) will be determined correctly. Our scope here is the long term matter of *how* to tax, not the short term matter of *how much* to tax.

## Implications for the Tax and Welfare System

So what are the implications of the macroeconomics of effective demand for tax policy? Firstly, tax policy, in redistributing income and wealth, can increase effective demand and growth. Second, management of the public debt is vital and should be considered in more detail, both from a fiscal perspective and from the point of view of the effects of interest rates on other asset classes (and therefore the interaction with taxes in these areas). In short, low interest rates increase the asset prices in other areas, and that effect can be mitigated by taxes in these areas. So reducing interest rates can be combined with a land value tax and higher taxes on companies.

# A1.5 The Price of Goods: Selling Cake Slices

Modern economics as taught tends to consist at an elementary and intermediate level of the marginalist analysis of Alfred Marshall. (At an advanced level it also includes the more complicated and mathematic treatment of Leon Walras's 'General Equilibrium' analysis. Here we focus on partial equilibrium)

What does this analysis consist of? And what is the relation to classical analysis? Let us consider John Stewart Mill's writing (as mentioned in Mark Blaug's book) because his theory shows that the later classical and neoclassical theory of price determination are equivalent. The classical theory is in some sense just bringing out special cases of the neoclassical theory. But those special cases are important. They are the distinctions that really make a difference.

OK, so let's first describe the neoclassical (Marshallian) theory. he neoclassical theory is very simple to describe: price is set at the intersection between supply and demand. 

As the price goes up, the amount demanded will, in general, fall. It goes down because fewer people are willing to pay.

The supply curve represents the amount of a particular good that will be supplied by firms at different price levels. So as the price of the good increases, it is in general assumed that there will be more firms able and willing to supply the good, and more of that good can be supplied.

## Classical Theory in Neoclassical terms

The classical theorists also had a theory of price and they focussed mostly on the supply side of the coin. Mill suggests three separate possible outcomes: the first when supply is in inelastic, the second when there's a completely competitive market and finally the last, when there's some diminishing returns, i.e. that the cost of production increases when the amount required increases.

The first case is the easiest. Imagine there is a completely fixed supply of something. For example, there's some plot of land in a desirable location. None of the locations around it are quite the same, and in any case, they are in limited supply also. Since the supply is fixed, the demand for that land is determined by the price that the market is willing to pay, and not by any cost of production (since there is no production: it's fixed in supply)

The second case is also straightforward. Imagine that there is a product that has a fixed cost of production and is made by a large number of competitive producers.

The final case is of diminishing returns. Imagine that there's some good, let's say oil, that is easy to produce in some places (say Saudi Arabia), but hard to produce in others (deep water drilling and oil shale). In the easy places, the cost of production is low, in the hard places the cost of production is high. In this case, the price of the good will be determined by the cost of production of the marginal producer, which is in turn determined by the demand schedule.

So the price of oil is determined by the cost of producing a marginal extra barrel of the market-demanded amount of oil. Of course the market demanded price of oil is itself dependent on price. That's why we intersect the demand and supply curve to see what's the price of oil. [Maybe change the above to grain instead??]

## Implications for Oil

Imagine we had a closed economy with a single government. The oil market shows the two types of taxes that could be imposed. A land value tax would be a tax on the surplus profit from owning some piece of land when oil is on. It does not shift the point of intersection but rather merely taxes the net profit of producing oil.

# A1.6 The Price of Assets: Selling Cake Shops

Now we mentioned that ownership of land gives rise to a surplus. But what about the value of the land? What would that be? We can consider therefore ownership of land as conferring that surplus. What should the value of that set of surplus flows be?

One method for analysing this is known as discounted cashflow analysis. This computes the value of a set of cashflows according to interest rates seen in the economy. So for example the value of a piece of land that pays £5000 per annum might be computed as 5000/r, where r is the long term interest rate. So for an interest rate of 0.05, the total value would be 5000/0.05 or £100,000. At a lower interest rate of 0.02, the value wold be 250,000.

What about if the value increases in time? Let's say that the rent goes up by 1% per year. In this case, the formula again wold be very simple a/(r-g) where g is the growth rate and r is the long term interest rate

# A1.7 Beyond Rationality: Do You Want A Slice Of Cake? 

In order to understand why the system is working the way it is, we need to take a look at the the tool-kit used to build it: mainstream neoclassical economics. 

Mainstream economics treats the world as being full of rational people, all looking to best maximise their own personal utility. This utility maximising tendency is the engine behind the flows of demand and supply that interact in efficient markets and influence price levels that then help distribute scarce goods in a  manner. However, people are not always rational, and markets are not always efficient. 

What does that mean for this brand of economics then? Clearly, a lot is missing.

Here we highlight three further missing aspects: time, space and life.

# A1.8 Time: Does the Cake Keep? 

Time is important because much economic activity is about storing value for the future. An example in simple terms would be when an individual stores financial assets (such as money) in a bank and the economic system grows these funds in investment opportunities and ensures that society, as a whole, increases its stock of wealth. That's the theory anyhow. One important factor in economics is ensuring that all this works effectively.

# A1.9 Space: Where's the nearest Cake Shop?

Space is important for two reasons. Firstly, each square metre of earth's surface is unique. It cannot be replicated. Thus, ownership of such a piece of land represents a monopoly in that it cannot be replicated.  Secondly, we all share in space. This means we all share in generating public goods in the space around us. This includes those created by the public and private sectors. We also share in creating public bads in the space around us, such as pollution.

Time and space interact with real estate. Since land is an infinitely lived monopoly (each piece of earth's surface is unique and lasts forever, for all practical purposes anyway), it has special features in terms of low interest rates. In other words, land is a long-lived asset and it becomes very valuable in low-interest rate environments. This was demonstrated in the follow up to the financial crisis.

# A1.10 Energy and Life: Preserving the Planetary Cake

Life is the third class of elements missing in mainstream economic thought. Living systems are fundamentally different from non-living systems. Living systems are typically in a state of homeostasis rather than equilibrium. This is a steady state which requires active maintenance and energy input.  For example,  it takes energy to maintain a constant body temperature of 3A1.7 Celsius. Biological systems also require certain environmental conditions and cannot exist beyond certain ecological limits. Ecological economics considers that human economy is embedded in nature and it argues for a sustainable economy that would also exist in a steady state ^[This alludes to an ecological / steady state economics approach. See: http://www.steadystate.org/discover/definition/]. So life is not only a crucial element to our planet that we need to preserve, but also a rich set of understandings of the fundamental nature of things. So just like 19th century and 20th century economics often uses analogies from the physical and engineering worlds, we need a new set of understandings based on the nature of life itself.

Human systems develop *capability*, and this capability is embodied in individuals, companies, networks and whole societies. Understanding capability both for private and public ends can allow us to progress further.
